name: chembind
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - pydantic
      - firebase-admin
      - python-dotenv


